name: flutter_game
description: Flutter game.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  audioplayers: ^3.0.1
  bloc: ^8.1.1
  equatable: ^2.0.5
  flame: ^1.6.0
  flame_audio: ^1.4.0
  flame_behaviors: ^0.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.3
  intl: ^0.18.0
  realm: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.1
  flame_test: ^1.9.2
  mockingjay: ^0.3.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/licenses/poppins/
